name: CI/CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.12', '1.11' ]
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependecies
        run: go get -v -t -d ./...
      - name: Run Unit tests
        run: go test -race -covermode atomic -coverprofile=profile.cov ./...
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -v -coverprofile=profile.cov -service=github
